export enum ConfigTypeEnum {
  securities = 'securities',
  assetClasses = 'asset-classes',
  assetLabels = 'asset-labels',
  investmentStrategies = 'investment-strategies',
  transactionCategories = 'transaction-categories',
  inboxDocumentCategories = 'inbox-document-categories',
  interviewQuestions = 'interview-questions',
  interviewAnswers = 'interview-answers',
  riskProfiles = 'risk-profiles',
  performanceProjections = 'performance-projections',
  countries = 'countries',
  industries = 'industries',
  assetIndustries = 'asset-industries',
  assetRegions = 'asset-regions',
  titles = 'titles',
  violations = 'violations',
}
