export enum FullWithdrawReasonEnum {
  shortTermExpences = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_HAVE_SHORT_TERM_EXPENSES',
  concernedByCapitalMarketDevelopements = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_AM_CONCERNED_BY_THE_CURRENT_CAPITAL_MARKET_DEVELOPMENTS',
  feesTooHigh = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.THE_FEES_ARE_TOO_HIGH',
  notHappyWithPerformance = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_AM_NOT_HAPPY_WITH_PERFORMANCE',
  notHappyWithProductFeatures = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_AM_NOT_HAPPY_WITH_THE_PRODUCT_FEATURES',
  customerServiceIsPoor = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.THE_CUSTOMER_SERVICE_IS_POOR',
  switchingToDifferentServiceProvider = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_AM_SWITCHING_TO_A_DIFFERENT_SERVICE_PROVIDER',
  doNotWantProvideReason = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_DO_NOT_WANT_TO_PROVIDE_A_REASON',
  other = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.OTHER',
}

export enum WithdrawReasonEnum {
  shortTermExpences = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_HAVE_SHORT_TERM_EXPENSES',
  concernedByCapitalMarketDevelopements = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_AM_CONCERNED_BY_THE_CURRENT_CAPITAL_MARKET_DEVELOPMENTS',
  profits = 'WITHDRAWAL_PAGE.WITHDRAW_REASONS.TAKE_SOME_PROFITS',
  leaving = 'WITHDRAWAL_PAGE.WITHDRAW_REASONS.THINKING_ABOUT_LEAVING',
  differentService = 'WITHDRAWAL_PAGE.WITHDRAW_REASONS.TRYING_OTHER_SERVICE_PROVIDER',
  doNotWantProvideReason = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.I_DO_NOT_WANT_TO_PROVIDE_A_REASON',
  other = 'WITHDRAWAL_PAGE.FULL_WITHDRAW_REASONS.OTHER',
}
